// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmI0clSNpa4OCss0CQaJi2tVxVfsaOeaQ',
    appId: '1:926965461052:web:8331f092181f93617c5339',
    messagingSenderId: '926965461052',
    projectId: 'app-banco-de-sangue',
    authDomain: 'app-banco-de-sangue.firebaseapp.com',
    storageBucket: 'app-banco-de-sangue.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7ONPihgAIUktcdIG1yXNJ6QAKyJXowtc',
    appId: '1:926965461052:android:3f9a50d19e988da27c5339',
    messagingSenderId: '926965461052',
    projectId: 'app-banco-de-sangue',
    storageBucket: 'app-banco-de-sangue.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ75oKbg4m2KSokvwARQlPGQmqwPluaPo',
    appId: '1:926965461052:ios:06a48b78eaf9dc3f7c5339',
    messagingSenderId: '926965461052',
    projectId: 'app-banco-de-sangue',
    storageBucket: 'app-banco-de-sangue.appspot.com',
    iosClientId: '926965461052-qd0m9v9fack8tiioqhivp1ot5dnqad4l.apps.googleusercontent.com',
    iosBundleId: 'com.example.appbancodesangue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ75oKbg4m2KSokvwARQlPGQmqwPluaPo',
    appId: '1:926965461052:ios:8c23e25543f5cef97c5339',
    messagingSenderId: '926965461052',
    projectId: 'app-banco-de-sangue',
    storageBucket: 'app-banco-de-sangue.appspot.com',
    iosClientId: '926965461052-om4326ck953e5msh921o9chfngq7obaj.apps.googleusercontent.com',
    iosBundleId: 'com.example.appbancodesangue.RunnerTests',
  );
}
